DATA:
  local_prefix: dataset/   # data_root prefix
  data_root: voc2012
  train_labeled_list: voc2012/list/voc_1464_labeled.txt
  train_unlabeled_list: voc2012/list/voc_1464_labeled.txt
  prediction_list: voc2012/list/voc_val.txt
  val_list: voc2012/list/voc_val.txt
  test_list: voc2012/list/voc_val.txt
  classes: 21

TRAIN:
  arch: psp
  layers: 50
  sync_bn: True  # adopt syncbn or not
  train_h: 321
  train_w: 321
  scale_min: 0.5  # minimum random scale
  scale_max: 1.5  # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  ignore_label: 255
  aux_weight: 0.4
  train_gpu: [0,1,2,3] # gpu id, change to [0,1,2,3,4,5,6,7] for 8-gpu
  workers: 8  # data loader workers
  batch_size: 16  # batch size for labeled data
  unlabelled_batch_size: 8  # batch size for unlabeled data
  batch_size_val: 8  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.01
  epochs: 50
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed: 1
  print_freq: 10
  save_freq: 10
  save_path: exp/
  exp_name: str
  weight: #initmodel/ex60.5.1_0.68_train_epoch_400.pth #initmodel/greedy_train_epoch_200.pth # path to initial weight (default: none)
  resume:  #initmodel/ST_iter0_0.6546_ex35.10_cf0.96_train_epoch_400.pth   # path to latest checkpoint (default: none)
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  evaluate_start: 44
  evaluate_freq: 2
  evaluate_full_size: True
  evaluate_previous_best_val_mIou: 0.0

  sup_loss_method: 'CE'   # 'MSE' 'CE' 'lovasz'
  consistency_lambda: 1.0
  only_label: True


Distributed:
  dist_url: tcp://127.0.0.1:6788
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0
  use_apex: True
  opt_level: 'O0'
  keep_batchnorm_fp32:
  loss_scale:

TEST:
  split: val  # split in [train, val and test]
  base_size: 400  # based size for scaling
  test_h: 321
  test_w: 321
  scales: [1.0]  # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
  has_prediction: False  # has prediction already or not
  index_start: 0  # evaluation start index in list
  index_step: 0  # evaluation step index in list, 0 means to end
  test_gpu: [0]
  model_path:  exp/ex36.7/model/train_epoch_400.pth  # evaluation model path
  save_folder: exp/
  colors_path: data/voc2012/voc2012_colors.txt  # path of dataset colors
  names_path: data/voc2012/voc2012_names.txt  # path of dataset category names
