DATA:
  local_prefix: dataset/   # data_root prefix
  data_root: cityscapes
  train_labeled_list: cityscapes/list/cs_split8_labeled_match_len.txt
  train_unlabeled_list: cityscapes/list/cs_split8_unlabeled_deeplabv2_cityscapes_split8_crop361_for_round1_DARS.txt
  prediction_list: cityscapes/list/cs_val.txt
  val_list: cityscapes/list/cs_val.txt
  test_list: cityscapes/list/cs_val.txt
  classes: 19

TRAIN:
  arch: deeplabv2
  layers: 101
  pretrain_data: imagenet
  sync_bn: True  # adopt syncbn or not
  train_h: 361
  train_w: 361
  scale_min: 0.25  # minimum random scale
  scale_max: 1.0  # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  ignore_label: 255
  aux_weight: 0.0
  train_gpu: [0,1] # gpu id, change to [0,1,2,3,4,5,6,7] for 8-gpu
  workers: 8  # data loader workers
  batch_size: 4  # batch size for labeled data
  unlabelled_batch_size: 4  # batch size for unlabeled data
  batch_size_val: 8  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.002
  epochs: 400
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed: 1
  print_freq: 10
  save_freq: 20
  save_path: exp/
  exp_name: str
  weight: # path to initial weight (default: none)
  resume:  initmodel/train_deeplabv2_cityscapes_split8_crop361_round0.pth  # path to latest checkpoint (default: none)
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  evaluate_start: 280
  evaluate_freq: 20
  evaluate_full_size: True
  evaluate_previous_best_val_mIou: 0.0

  sup_loss_method: 'CE'   # 'MSE' 'CE' 'lovasz'
  consistency_lambda: 1.0
  only_label: False


Distributed:
  dist_url: tcp://127.0.0.1:6788
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0
  use_apex: True
  opt_level: 'O0'
  keep_batchnorm_fp32:
  loss_scale:

TEST:
  split: val  # split in [train, val and test]
  base_size: 1024  # based size for scaling
#  test_h: 713
  test_h: 361
#  test_w: 713
  test_w: 361
  scales: [1.0]  # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
  has_prediction: False  # has prediction already or not
  index_start: 0  # evaluation start index in list
  index_step: 0  # evaluation step index in list, 0 means to end
  test_gpu: [0]
  save_folder: exp/
  colors_path: data/cityscapes/cityscapes_colors.txt  # path of dataset colors
  names_path: data/cityscapes/cityscapes_names.txt  # path of dataset category names
